### ISSUE TITLE
Failing Auth, "user not found"?

### ISSUE THREAD

**Issue by pzrd** [DIGITALCRIMINAL/OnlyFans#1010]
I have been using an older version of the script (5.3) for some time now with no problems, but now I'm getting an issue where the console is telling me my User cannot be found. I've checked over my settings multiple times and see everything is fine and matches the cookies and my OF username, yet still no dice. 

![SS_110421-142930](https://user-images.githubusercontent.com/82322348/114306069-8fb8e180-9ad2-11eb-811c-97264834f152.png)

**Comment by cdemi** [comment]
Yes I can confirm this is also an issue on my end. I think OF must have started verifying some other parameters as well

**Comment by Sumnus456** [comment]
Getting this issue as well. Tried using the normal username that worked previously as well as "u<auth_id>" which was being pulled by some cookies, and neither worked.

**Comment by LunarPenguin** [comment]
It seems you are using a rather old version since the most recent version is `6.4.4`. OnlyFans makes periodic changes to their api making it necessary to change the code to reflect those changes. i would suggest upgrading to a newer version of the software as it appears this one is from august 17 2020 and thus being almost a year old.

**Comment by DIGITALCRIMINAL** [comment]
>Uses an outdated version
>Asks why it isn't working
