### ISSUE TITLE
I can't scrap paid content

### ISSUE THREAD

**Issue by Techttv** [DIGITALCRIMINAL/OnlyFans#1026]
I can't scrap paid content but in config file the option is true

**Comment by neokrypt47** [comment]
same issue here.

**Comment by LunarPenguin** [comment]
If you want to download paid content which you did not pay for then that's never going to work, ever.

if you pay to unlock paid content the software will download it, otherwise it wont. You gotta pay to play

if you did pay for it and it is not working please share the output of the software and make sure to edit out any personal info

**Comment by mrtajniak** [comment]
Will it be possible to download paid content without paying in the future, for sure, there is a possibility because nothing is perfect. ...right?
