### ISSUE TITLE
There's nothing to scrape

### ISSUE THREAD

**Issue by mooseyoose** [DIGITALCRIMINAL/OnlyFans#1030]
`Names: Username = username  |  0 = All | 1 = default

planesgirl
Scraping Paid Content
Scraping Subscriptions
There's nothing to scrape.
Archive Completed in 0.28 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit
`

I'm getting "there's nothing to scrape" when I try to download content. I know for a fact that there's content on the profile. But it won't download. Any ideas? thanks.

**Comment by mooseyoose** [comment]
I've doubled checked the auth. Still nothing to scrape

**Comment by LunarPenguin** [comment]
could you properly format your output? its hard to read currently.

> I've doubled checked the auth. Still nothing to scrape

i believe you but 9 out of 10 of these problem are because of bad auth. i suggest you try a couple more times and if it then still doesnt work we'll see what we can do

**Comment by YouthGarage** [comment]
Same Problem

**Comment by chidi9901** [comment]
Honestly, double check like every single line of auth. Even with the latest commit, I just replaced the files to update and I didn't even need to update auth. and it still scrapped wonderfully.

**Comment by YouthGarage** [comment]
I got it to work by using mail and password as auth.

**Comment by requader** [comment]
> 
> 
> I got it to work by using mail and password as auth.

Could you clarify and paste what you did?

**Comment by arsaequi** [comment]
Did you fix the problem already, because I've got the same problem?

For me it is the case that it doesn't matter if I make use of the scraper through cookies or web browser login (gecko driver), both ways give me as result that there is nothing to scrape. Even though there is enough paid/unpaid content to scrape.

So my auth.json file is complete and correct for sure. Could it be something in the config.json file?

**Comment by arsaequi** [comment]
> I got it to work by using mail and password as auth.

What do you mean exactly?

**Comment by drobb0690** [comment]
im honestly having the same issues now.  i was having others but i figured those out to be something wrong with my confif.json and i just had the script regenerate it but now im getting this.

Scraping Paid Content
Scraping - nerdydirtycosplay | 0 / 1
Scraping [photo]. Should take less than a minute.
Scraping [video | stream | gif]. Should take less than a minute.
Scraping [audio]. Should take less than a minute.
Scraping [text]. Should take less than a minute.
Processing metadata.
Finished processing metadata.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
Renaming files.
Scraping Subscriptions
There's nothing to scrape.
Download Processing
Name: nerdydirtycosplay | Type: Posts | Count: 724 Images | Directory: G:\OnlyFans-master\OnlyFans-master\.sites

0.00B [00:00, ?B/s]
Download Processing
Name: nerdydirtycosplay | Type: Posts | Count: 47 Videos | Directory: G:\OnlyFans-master\OnlyFans-master\.sites

0.00B [00:00, ?B/s]
Archive Completed in 0.08 Minutes
Pausing scraper for 0 seconds.
Site: 0 = onlyfans | x = Exit


it will at least try and download the 1 thing ive paid for, and if i tell it to overwrite files it will donwnload it again so that works its just not seeing anything else.   ive redid my auth and even tried browser auth and ive gone through and checked and changed and tried just about every single thing i can change in config as well with no luck.  help please would be appreciated.

**Comment by xblubbx2** [comment]
Auth with auth_id and sess suddenly wasn't possible anymore. I switched to email and password, that works. However, says "There's nothing to scrape."
