### ISSUE TITLE
How you guys are calculating these parameters? They are producing wrong sign as compare to the request by browser

### ISSUE THREAD

**Issue by EhtishamSabir** [DIGITALCRIMINAL/OnlyFans#1148]
{
    "static_param": "cyo3uhuZp5tqYuEAhaVMuXMmPpRRsBq1",
    "format": "7:{}:{:x}:6092eb4c",
    "checksum_indexes": [25, 35, 26, 34, 32, 35, 32, 6, 21, 2, 15, 9, 3, 14, 26, 26, 5, 34, 30, 34, 30, 23, 12, 20, 20, 26, 17, 35, 5, 16, 37, 1],
    "checksum_constant": -956,
    "error_code": 0,
    "message": ""
}

**Comment by hippothon** [comment]
The actual signature should be correct and valid.
The only thing thats changed over the past couple days is the last bit `6092eb4c`, which is a timestamp whos true purpose is unknown.

It doesn't make the signature invalid and it doesn't force a refresh so a real browser user could be using an old value, so I haven't been pushing changes here since it doesn't seem to matter.

**Comment by naxolotl** [comment]
It would still be better to keep this updated. In the long run, the age of the sign will become one of the identifying factors that they can use to block scraping users. They could have done this a long time ago using API usage statistics, but the fact that they are now actively trying to stop scraping, probably means that management made it a priority.

**Comment by kallenkozuki** [comment]
These mofos think they can stop me? Show them the power of Javascript.
