### ISSUE TITLE
Auth (V1) Attempt 1-10 error

### ISSUE THREAD

**Issue by Fall0n** [DIGITALCRIMINAL/OnlyFans#116]
C:\temp\OnlyFans-master>StartDatascraper.py
Site: 0 = onlyfans | 1 = justforfans | 2 = 4chan | 3 = bbwchan
0
Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10

Have add my app-token, auth_id, auth_hash, sess

what have i done wrong?

**Comment by DIGITALCRIMINAL** [comment]
Did you add your user_agent?

**Comment by Fall0n** [comment]
Yes i have add that. I might have misunderstood it. It will be my browser. Not just the characters and numbers as in the others I will add

**Comment by DIGITALCRIMINAL** [comment]
Has to be the whole user-agent string

**Comment by Fall0n** [comment]
yes it all the text that that i did get from dev-tool.. and i get this error that i did post..

**Comment by Fall0n** [comment]
Is there a way you can take a look on my config.json and see. i can add other info. And you can see what i done wrong..

**Comment by DIGITALCRIMINAL** [comment]
@Fall0n I can, you can just email me it

**Comment by Fall0n** [comment]
Did add other text/info.. But it is written in exactly the same way.
Email it in 1sec

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DIGITALCRIMINAL** [comment]
It's supposed to look this this
https://user-images.githubusercontent.com/21285176/71552061-010f7680-29ed-11ea-8f4d-63702ae5ae7c.png

**Comment by ipkpjersi** [comment]
I'm also getting this error, and have been getting it since like some time in December. Glad to see it's not just me.

My auth credentials are correct. auth_id, auth_hash, sess, app-token are all filled in and correct *and* they aren't outdated, I filled them out again today yet it is still not working, it loops through Auth (V1) Attempt 1-10 endlessly:

![](http://i.imgur.com/bf6miqs.png)

![](http://i.imgur.com/0QkTcY0.png)

The weird thing is, I believe it used to do Auth (V2) and that would get it to authenticate successfully, however it never gets past Auth (V1) anymore.

**Comment by DIGITALCRIMINAL** [comment]
@ipkpjersi Ah yes, for some reason I took out auth v2...

**Comment by DIGITALCRIMINAL** [comment]
@ipkpjersi download the latest commit pls. Updated with auth V2

**Comment by ipkpjersi** [comment]
I tested and Auth V1 and V2 weren't working still, but just now I updated my user-agent and now it's working again. Thanks.
