### ISSUE TITLE
Ability to keep download history to avoid redownloading files?

### ISSUE THREAD

**Issue by sideloading** [DIGITALCRIMINAL/OnlyFans#1575]
Is there any way to keep a download history file to avoid redownloading previously downloaded media? This is particularly useful on a limited storage VPS, where I am moving storage data to the cloud once scraping is finished. 

Thank you

edit: using rclone mount works as a workaround: `rclone mount remote:path/to/files /path/to/local/mount --vfs-cache-mode writes`

**Comment by ThrowawayDane** [comment]
Move your Metadata to another directory that is not in the same folder as your creator in config.json because as long the script can read the Metadata it remebers what you have downloaded but if you remove the Metadata it will redownload everything. 

I have mine setup to keep metadata on my linux box like this: /media/Metadata this is on one nfs share and it will then download the files to /media/OnlyFans and this is on another nfs share.

So in that way i will be able to reinstall the linux box and just mount the shares again so it will not redownload everything on the first run and i keep the metadata files away from the creators folders as that can have some data that can link to you.

**Comment by sideloading** [comment]
@ThrowawayDane Thank you!
