### ISSUE TITLE
Option to not download promotion posts

### ISSUE THREAD

**Issue by CaptainJawZ** [DIGITALCRIMINAL/OnlyFans#338]
So I'm not sure what's the actual name of these posts, but I've noticed that recently a lot of models put limited time posts to promote other models.
On the timestamp, there is a small sand clock icon, and on the bottom of these posts there is a baner to subscribe to another onlyfans page. 

These posts usually include a preview photo/video of that other OF page, and I was wondering if there is a way to not download those, cuz it's a bit annoying to go to my OF videos folders and find a bunch of videos of other models that I'm not interested in. Please and thank you!

**Comment by artyom2035** [comment]
Concur, this would be nice if it's possible. I unsubscribed from paid accounts because I was getting more promotions than actual content. Model said she had been paid for the entire July to post the to wall and MESSAGES, daily! Note: Free accounts are the worst at this.

As a workaround, I've been trying "ignore_keywords" to filter promotions out by some of their buzz words & catch-phrases. One drawback is the list appears to be case-sensitive, e.g., it'll only catch FOLLOW and Follow if you put both in the config. 

So, it takes a lot of effort to manage, some still slip through and you inevitably block some content that you want. Also, keywords don't work if the model only posts a graphic without a caption.  I'm up to 310 words - most in phrases - and still download 5-10 promos daily but it was probably 50-60 beforehand. I follow ~30 accounts, some free.

![Annotation 2020-07-25 000612](https://user-images.githubusercontent.com/29996283/88449259-0a3db600-ce0b-11ea-9a16-211c0b4245ab.png)

**Comment by CaptainJawZ** [comment]
Thats an idea, but do those posts follow a special format that would allow them to be easily filtered out? or do they have the same structure as any other post which would make them harder to separate? in which case the ignore keywords sounds like the best idea.

**Comment by artyom2035** [comment]
I guess they could be identifiable by the code that the hourglass/countdown timer uses. I'm no programmer, so I couldn't find it.  I wanted to, but didn't create another issue since he gets so many frivolous ones, so I just used keywords.  

I also wanted to add my support for your request & point out that while keywords kinda works, it's very inefficient. Just in case someone came here and said "Just use ignore_keywords"

**Comment by aboredpervert** [comment]
I have implemented it very quickly in https://github.com/aboredpervert/OnlyFans/commit/edfeaea1ce4487e1378732def5ecceabeefbe984 but it probably needs a setting, and some documentation.

**Comment by DIGITALCRIMINAL** [comment]
Ignored keywords would be the best choice otherwise you'd be getting false positives

**Comment by dharrisvelaro** [comment]
Any ideas on how you can do that with the ignore keywords? I attempted to key off ID "icon-clock" but that didn't seem to work.

**Comment by CaptainJawZ** [comment]
Would any of these work?

In addition to the clock icon for the timed posts that get deleted after a couple of days, all of these posts have a special reference banner for the mentioned user (being promoted) 

Any way to add any of this info to the blacklist or filter? 

Looks like this 
![image](https://user-images.githubusercontent.com/43111068/93389154-62080480-f831-11ea-8dc0-53370fa08695.png)


`<div class="row row_flex b-post__mentioned-users-list"><div class="col-xs-12"><div class="b-friend"><a href="/andrian_grey" class=""><div class="b-friend__cover-wrapper"><img src="https://public.onlyfans.com/files/thumbs/w480/w/wp/wpc/wpcuoz48cazcjs8t61bsbxe7lazlaupz1600076732/header.jpg" alt="Adrian Gray" class="b-friend__cover"></div><div class="b-free-label"><!----><svg class="g-icon m-has-promo" aria-hidden="true"><use xlink:href="#icon-discount" href="#icon-discount"></use></svg></div><div class="b-friend__content"><div class="b-friend__avatar"><span class="g-avatar online_status_class m-w150 m-border-line"><!----><img src="https://public.onlyfans.com/files/thumbs/c144/d/d4/d4s/d4sj6mofc8pqyrpejcvb8kzz7fnh5qbg1600076732/avatar.jpg" alt="Adrian Gray"><!----></span></div><div class="b-username-row"><div class="b-username m-like-link"><div class="g-user-name m-lg-size"> Adrian Gray <!----></div></div></div><div class="b-username-row"><div class="b-username"><div class="g-user-username"> @andrian_grey </div></div></div></div></a><div class="dropdown b-dropdown m-btn-vertical-dots m-center m-reset-gaps m-light m-not-width-limit m-radial-gradient-btn btn-group" id="__BVID__158"><!----><button aria-haspopup="true" aria-expanded="false" type="button" class="btn dropdown-toggle btn-link" id="__BVID__158__BV_toggle_"><svg class="g-icon has-tooltip" aria-hidden="true" data-original-title="null"><use xlink:href="#icon-more" href="#icon-more"></use></svg></button><ul role="menu" tabindex="-1" class="dropdown-menu dropdown-menu-right" aria-labelledby="__BVID__158__BV_toggle_"><li role="presentation"><button role="menuitem" type="button" class="dropdown-item"> Agregar a/eliminar de listas </button></li><!----></ul></div></div></div></div>`

**Comment by DIGITALCRIMINAL** [comment]
That's all HTML so it doesn't help
