### ISSUE TITLE
Log Fille

### ISSUE THREAD

**Issue by RickyBubbles** [DIGITALCRIMINAL/OnlyFans#359]
Is it possible to get some sort of verbose logging for the scraper?
I’ve gotten a few random hangs, and it’s hard for me to guess where the problem lies with no log...
My guess is that it has something to do with the way the script is checking for duplicates to see which files to skip, but I’m not sure. My drive is a network drive not a local drive so it may not behave the same way as a regular file system....

**Comment by DIGITALCRIMINAL** [comment]
@RickyBubbles are you using GSuite Drive?

**Comment by RickyBubbles** [comment]
> @RickyBubbles are you using GSuite Drive?

Yes, via rclone

**Comment by DIGITALCRIMINAL** [comment]
I use Drive without rclone, sometimes it will hang when there's a lot of operations going on with Drive.

**Comment by dr-mcgillicuddy** [comment]
Disabling date updates in rclone (e.g. mod time doesn’t change when opening a file) seems to improve things... does that mean anything to you? I’m not sure what (if any) significance that might have.

I would expect some lag because Google limits file creation to one per second (ish) so it probably can’t make files as fast as the scraper downloads them, but not a complete stall. I may run my next scrape without multithreading and see if that helps.

**Comment by RickyBubbles** [comment]
I think it may have to do with how the scraper sets modification times on the files, but I’ll have to play around with it a little more. What I think happens is that when the script checks the file to see if it’s a dupe, Google updates the modification time, but the script also tries to revert the mod time to match the post time and the drive API gets confused... does that sound possible too you?

**Comment by DIGITALCRIMINAL** [comment]
Sometimes the script would download the wrong image or video which would result in it uploading multiple times.
