### ISSUE TITLE
Add support for recurbate.com

### ISSUE THREAD

**Issue by rabea98** [DIGITALCRIMINAL/OnlyFans#459]
Hi,
Could you consider adding support for https://recurbate.com/ ?

**Comment by gitporn873** [comment]
Recurbate is a bit difficult unless you pay for Premium account. As a free user you could only really grab 3 videos a day which would make grabbing all of a model's videos super time consuming. 

In case the option to add this functionality gets discussed more seriously I did a quick check of feasibility. Given an (ideally Premium) account and it seems simple enough to do. Here's a bunch of cursory info:

**Get Model video index:**

```
https://recurbate.com/?performer=<Model Name (str)>
```

**Navigate pagination:**

```
https://recurbate.com/?page=<Page Number(int)&performer=<Model Name (str)>
```
_Note: There is no "last" button on the pagination only "Next »" which disappears on last page. Pagination would ideally check to see if the last `<li>` element of class `page_item` has a child `<a>` element with a `<span>` equal to `Next&nbsp;»`. If so the script would click the 2nd to last `page_item` and continue the check until there is no "Next" button. At which point the script know the last `<li>` of class `page_item` contains the `<a>` with the value of the last page of a model's index. This would speed up scraping vs clicking "Next" over and over and over again to get the last page. Some models I checked have 30 pages worth of content so minimizing the pagination crawl is obviously useful_

**Get Video ID:**

From the model's video index there is a `<div>` with class `video-thumb` for each video on the page. Within this `<div>` there is an `<a>` element which contains `/play.php?video=<Video ID (int)>` as its href value. Fairly easy to grab these.

**Get the CDN link to video:**

```
https://recurbate.com/api/get.php?video=<VIDEO ID (int)>
```

I was messing around and forgot to preserve network logs to see the exact response given when you successfully issue the `get.php` api request but you end up being returned a url that looks like this:

```
https://f08.frontgross.com/<Model Name (str)>/<Year (int)>-<Month (int)>-<Day (int)>,<Hour as 24 hour clock (int)>-<Minute (int)>.mp4?md5=r3Y2e4BC87CWjXWUlWi-pA&expires=1603313586&origin=103&mid=ac406220-8a39-4b21-9fe1-bad28c5c53ff
```

`md5` seems to be some serialized version of an md5 hash but even then it's not enough characters so idk.  

`expires` is a unix timestamp based on UTC and is about an hour into the future from the request to `get.php`.  

`origin` ??? probably static tbh.  

`mid` appears to be a GUID/UUID for "member ID". This value is part of the cookies set after logging in. 


**Cookies:**

Example dump of cookies with some information redacted.

```
__cfduid=d4ca58672321f6082df2baf982a3231421603308461; mid=********-****-****-****-********; mid_ets=1918668462; mid_its=1603308462; im18=true; im18_ets=1603913285; im18_its=1603308485; akey=********-****-****-****-************; akey_ets=1603827004; akey_its=1603308604
```

`__cfduid` is a Cloudflare identifier, probably not needed for proper authentication.  

`mid` is the GUID/UUID of a member ID and is used to construct the CDN url for videos. String of lowercase hex characters chunked in sets of 8-4-4-4-12. Probably important for session management/login.  

`mid_ets` appears to be the unix timestamp (in UTC) for when either the member ID expires or the session expires. Currently unsure but it is set to 10 years in the future minus 2 days. Probably important for session management/login.  

`mid_its` need to investigate by making a new account. It's either the timestamp of a user login and thus used for session information, or it's the time a member ID was created and tied to additional session checking on the `mid`. Probably important for session management/login.  

`im18` just set to true, means you claimed to be 18 years or older.  

`im18_ets` unix timestamp (in UTC) checked to see if site will prompt you for age confirmation again. Currently set to 7 days in the future.  

`im18_its` unix timestamp (in UTC) when user agreed they were 18.  

`akey` GUID/UID unsure of exactly how it's set or calculated but probably means "auth key" or similar. String of lowercase hex characters chunked in sets of 8-4-4-4-12. Probably pretty important for session management/login.  

`akey_ets` unix timestamp (in UTC) for when `akey` expires. Currently set to about 6 days in the future. Probably important for session management/login.  

`akey_its` unix timestamp (in UTC) for when `akey` was created. Probably important for session management/login.

**Scraping**

So as I see it, there are two possible ways to go about scraping. One way I know for sure would work as it's the exact same way the typical userflow is:

1. User logs into website normally and gets the appropriate cookie values needed. Pastes those into the config file.
2. Script prompts for model to scrape
3. Script requests model page, begins pagination to determine final page of results for a model's videos.
4. Script grabs all the Video ID's on the current page of a model's index and then goes on to the next page until all pages have been scraped.
5. Script then iterates through all the Video ID's and issues a GET request to the `get.php` API endpoint.
6. Recurbate returns the CDN URL for the video and script can download the video.

The second way is definitely more work but could skip a few steps if it works/research is done. Requires determining how the `md5` value of the CDN URL is calculated (which might be impossible as it is possibly a version of the md5 of the actual file on their CDN). With the md5 calculated (or somehow determined), the model name (which the script knows as it is scraping that model), the cookies provided to the script in `config.json`, and the date on the video (displayed on the model's index) it's definitely possible to create a CDN link that would work. While this method would reduce the amount of calls the script would have to make and streamline things a bit, I'd definitely only recommend it as a last resort if Recurbate starts doing a lot of anti-bot stuff.

@rabea98 if you have a Premium account and don't mind sharing credentials I could probably take a stab at writing you a scraper. I don't know much of how the codebase for this repo's scraper work but I'd be down to do it as a separate repo and PoC so that it could possibly be ported over to work with DigitalCriminal's project.

**Comment by dilemmax** [comment]
@gitporn873 wow. That is such a comprehensive response for @rabea98. Do you think you can help with a scrapper for Justforfans? Digitalcriminal is not interested in supporting the old scrapper unless the website uses API. Some of the models have moved from OnlyFans to Justforfans after the Bella Thorne fiasco.

**Comment by rabea98** [comment]
> **Edit: I'm sorry in advanced if I took things a bit out of bound for this issue @DIGITALCRIMINAL . Also not trying to steal away people from your userbase or hijack or your project with my suggestion further below. Only trying to help out OP while providing a PoC project in case you decide to implement such functionality here. Again, sorry in advanced if my comment is inappropriate.**.
> 
> Recurbate is a bit difficult unless you pay for Premium account. As a free user you could only really grab 3 videos a day which would make grabbing all of a model's videos super time consuming.
> 
> In case the option to add this functionality gets discussed more seriously I did a quick check of feasibility. Given an (ideally Premium) account and it seems simple enough to do. Here's a bunch of cursory info:
> 
> **Get Model video index:**
> 
> ```
> https://recurbate.com/?performer=<Model Name (str)>
> ```
> 
> **Navigate pagination:**
> 
> ```
> https://recurbate.com/?page=<Page Number(int)&performer=<Model Name (str)>
> ```
> 
> _Note: There is no "last" button on the pagination only "Next »" which disappears on last page. Pagination would ideally check to see if the last `<li>` element of class `page_item` has a child `<a>` element with a `<span>` equal to `Next&nbsp;»`. If so the script would click the 2nd to last `page_item` and continue the check until there is no "Next" button. At which point the script know the last `<li>` of class `page_item` contains the `<a>` with the value of the last page of a model's index. This would speed up scraping vs clicking "Next" over and over and over again to get the last page. Some models I checked have 30 pages worth of content so minimizing the pagination crawl is obviously useful_
> 
> **Get Video ID:**
> 
> From the model's video index there is a `<div>` with class `video-thumb` for each video on the page. Within this `<div>` there is an `<a>` element which contains `/play.php?video=<Video ID (int)>` as its href value. Fairly easy to grab these.
> 
> **Get the CDN link to video:**
> 
> ```
> https://recurbate.com/api/get.php?video=<VIDEO ID (int)>
> ```
> 
> I was messing around and forgot to preserve network logs to see the exact response given when you successfully issue the `get.php` api request but you end up being returned a url that looks like this:
> 
> ```
> https://f08.frontgross.com/<Model Name (str)>/<Year (int)>-<Month (int)>-<Day (int)>,<Hour as 24 hour clock (int)>-<Minute (int)>.mp4?md5=r3Y2e4BC87CWjXWUlWi-pA&expires=1603313586&origin=103&mid=ac406220-8a39-4b21-9fe1-bad28c5c53ff
> ```
> 
> `md5` seems to be some serialized version of an md5 hash but even then it's not enough characters so idk.
> 
> `expires` is a unix timestamp based on UTC and is about an hour into the future from the request to `get.php`.
> 
> `origin` ??? probably static tbh.
> 
> `mid` appears to be a GUID/UUID for "member ID". This value is part of the cookies set after logging in.
> 
> **Cookies:**
> 
> Example dump of cookies with some information redacted.
> 
> ```
> __cfduid=d4ca58672321f6082df2baf982a3231421603308461; mid=********-****-****-****-********; mid_ets=1918668462; mid_its=1603308462; im18=true; im18_ets=1603913285; im18_its=1603308485; akey=********-****-****-****-************; akey_ets=1603827004; akey_its=1603308604
> ```
> 
> `__cfduid` is a Cloudflare identifier, probably not needed for proper authentication.
> 
> `mid` is the GUID/UUID of a member ID and is used to construct the CDN url for videos. String of lowercase hex characters chunked in sets of 8-4-4-4-12. Probably important for session management/login.
> 
> `mid_ets` appears to be the unix timestamp (in UTC) for when either the member ID expires or the session expires. Currently unsure but it is set to 10 years in the future minus 2 days. Probably important for session management/login.
> 
> `mid_its` need to investigate by making a new account. It's either the timestamp of a user login and thus used for session information, or it's the time a member ID was created and tied to additional session checking on the `mid`. Probably important for session management/login.
> 
> `im18` just set to true, means you claimed to be 18 years or older.
> 
> `im18_ets` unix timestamp (in UTC) checked to see if site will prompt you for age confirmation again. Currently set to 7 days in the future.
> 
> `im18_its` unix timestamp (in UTC) when user agreed they were 18.
> 
> `akey` GUID/UID unsure of exactly how it's set or calculated but probably means "auth key" or similar. String of lowercase hex characters chunked in sets of 8-4-4-4-12. Probably pretty important for session management/login.
> 
> `akey_ets` unix timestamp (in UTC) for when `akey` expires. Currently set to about 6 days in the future. Probably important for session management/login.
> 
> `akey_its` unix timestamp (in UTC) for when `akey` was created. Probably important for session management/login.
> 
> **Scraping**
> 
> So as I see it, there are two possible ways to go about scraping. One way I know for sure would work as it's the exact same way the typical userflow is:
> 
> 1. User logs into website normally and gets the appropriate cookie values needed. Pastes those into the config file.
> 2. Script prompts for model to scrape
> 3. Script requests model page, begins pagination to determine final page of results for a model's videos.
> 4. Script grabs all the Video ID's on the current page of a model's index and then goes on to the next page until all pages have been scraped.
> 5. Script then iterates through all the Video ID's and issues a GET request to the `get.php` API endpoint.
> 6. Recurbate returns the CDN URL for the video and script can download the video.
> 
> The second way is definitely more work but could skip a few steps if it works/research is done. Requires determining how the `md5` value of the CDN URL is calculated (which might be impossible as it is possibly a version of the md5 of the actual file on their CDN). With the md5 calculated (or somehow determined), the model name (which the script knows as it is scraping that model), the cookies provided to the script in `config.json`, and the date on the video (displayed on the model's index) it's definitely possible to create a CDN link that would work. While this method would reduce the amount of calls the script would have to make and streamline things a bit, I'd definitely only recommend it as a last resort if Recurbate starts doing a lot of anti-bot stuff.
> 
> @rabea98 if you have a Premium account and don't mind sharing credentials I could probably take a stab at writing you a scraper. I don't know much of how the codebase for this repo's scraper work but I'd be down to do it as a separate repo and PoC so that it could possibly be ported over to work with DigitalCriminal's project.

@gitporn873 Firts of all, Thanks for the response and for your interest in this work. And thanks for the technical explanation.
I'm going to buy a membership right now for this project, how do i send you the credentials? do you prefer that we move to another platform such as mastodon ? or telegram ?

**Comment by gitporn873** [comment]
> @gitporn873 wow. That is such a comprehensive response for @rabea98. Do you think you can help with a scrapper for Justforfans? Digitalcriminal is not interested in supporting the old scrapper unless the website uses API. Some of the models have moved from OnlyFans to Justforfans after the Bella Thorne fiasco.

I could definitely look into it but I'm not trying to hijack this project or anything and definitely not looking to actively maintain a scraper project. What Digitalcriminal has done with this scraper is honestly incredible and I'm surprised he actively maintains this.

> **@gitporn873 Firts of all, Thanks for the response and for your interest in this work. And thanks for the technical explanation. I'm going to buy a membership right now for this project, how do i send you the credentials? do you prefer that we move to another platform such as mastodon ? or telegram ?**

Telegram is fine. Username is g_montag

**Comment by rabea98** [comment]
> g_montag

I sent you a message on telegram

**Comment by dilemmax** [comment]
@gitporn873 JFF was last supported around version 3.4. If you are interested and you need a paid account to work from, have a look at the website and let me know which model you are interested in.

@rabea98 Sorry for hijacking your post!! I couldn't PM @gitporn873 on Github for some reason....
