### ISSUE TITLE
SQLite metadata no longer contains message or post text

### ISSUE THREAD

**Issue by clydachpugsley** [DIGITALCRIMINAL/OnlyFans#670]
Since the change the new .db files no longer have the bulk of the important information,the message and post text data.
It only contains
id,post_id,link,directory,filename,size,media_type,downloaded,created_at. The "text" field from the JSON files was not converted and is not grabbed upon when starting a new fresh scrape. "price" would be a nice field to also have in the new db

**Comment by DIGITALCRIMINAL** [comment]
Yes it does

![image](https://user-images.githubusercontent.com/21285176/103812613-acb6c200-5056-11eb-8a4d-7473d85b68e4.png)

**Comment by DIGITALCRIMINAL** [comment]
> > Yes it does
> > http://inloop.github.io/sqlite-viewer/
> > ![image](https://user-images.githubusercontent.com/21285176/103812613-acb6c200-5056-11eb-8a4d-7473d85b68e4.png)
> 
> It dosent show it in the main table and having it separate from the rest of the data is rather useless. It was never presented this way in the json file. Price isnt populated on paid content

It's a database, there is no "main table".
All you have to do is search for the message-id in the media table and it will give you the related items.

**Comment by clydachpugsley** [comment]
There should not be 2 tables,the data is from one data set and that is how it was reflected in the json since forever. Right now you have to merge all the shit in to one table your self and not follow the original metadata structure

**Comment by DIGITALCRIMINAL** [comment]
> There should not be 2 tables,the data is from one data set and that is how it was reflected in the json since forever. Right now you have to merge all the shit in to one table your self and not follow the original metadata structure

How are YOU telling ME there should not be two tables? You have no idea have to use databases since you couldn't even find where 2nd table is. The JSON file has been going through multiple changes.

Lmao if I actually listened to your silly suggestion of adding the text column in the media table the database would TRIPLE in size and no one wants that.

It's the same metadata and I don't need someone who hasn't worked on the script to tell me that it's not. Go research what a relational database is because you clearly do not know.

**Comment by DIGITALCRIMINAL** [comment]
> There should not be 2 tables,the data is from one data set and that is how it was reflected in the json since forever. Right now you have to merge all the shit in to one table your self and not follow the original metadata structure

How are YOU telling ME there should not be two tables? You have no idea how to use databases since you couldn't even find where 2nd table is. The JSON file has been going through multiple changes.

Lmao if I actually listened to your silly suggestion of adding the text column in the media table the database would TRIPLE in size and no one wants that.

It's the same metadata and I don't need someone who hasn't worked on the script to tell me that it's not. Go research what a relational database is because you clearly do not know.
