### ISSUE TITLE
Traceback (most recent call last) failure

### ISSUE THREAD

**Issue by goodboi69** [DIGITALCRIMINAL/OnlyFans#717]
New install. Updated pip requirements. I open the ripper and this is the first message I get.

> Traceback (most recent call last):
  File "X:\Programs\OnlyFans\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "X:\Programs\OnlyFans\datascraper\main_datascraper.py", line 48, in start_datascraper
    apis = main_helper.process_profiles(
  File "X:\Programs\OnlyFans\helpers\main_helper.py", line 549, in process_profiles
    temp_json_auth = ujson.load(
ValueError: Expected object or value

**Comment by olivechicago** [comment]
https://github.com/DIGITALCRIMINAL/OnlyFans/issues/710

**Comment by olivechicago** [comment]
I don't know if it worked for you, but it did not for me.  After deleting both the .profile and .settings json files, I get the following error.  I triple checked the required cookie data, and they appear to be correct.  The fact that auth failed all 10 times I even tried after setting "support_2fa" to _false_ since _true_ is the default and I don't use 2fa there.

Oddly enough, after running the script fails, it changes "active" to false.

Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Scraping Paid Content
Traceback (most recent call last):
  File "D:\ExePrograms\onlyfans\start_ofd.py", line 40, in <module>
    main_datascraper.start_datascraper(json_config, site_name_lower)
  File "D:\ExePrograms\onlyfans\datascraper\main_datascraper.py", line 85, in start_datascraper
    paid_content = module.paid_content_scraper(apis)
  File "D:\ExePrograms\onlyfans\modules\onlyfans.py", line 304, in paid_content_scraper
    author = paid_content.get("author")
AttributeError: 'str' object has no attribute 'get'

**Comment by olivechicago** [comment]
It looks like Onlyfans kills my session when the script fails.  I have to log back in every time.

**Comment by DIGITALCRIMINAL** [comment]
> It looks like Onlyfans kills my session when the script fails. I have to log back in every time.

That means you're entering your details wrong.
