### ISSUE TITLE
wrong user login

### ISSUE THREAD

**Issue by dean78901** [DIGITALCRIMINAL/OnlyFans#77]
the issue in 52 seems to still persist - not sure entirely how to replicate - usually after running a scrape task for some time.  Curious, how does this happen if the system is passing the user specific auth details form the .json file?

**Comment by DIGITALCRIMINAL** [comment]
Yeah, that's down to OnlyFans. I have no idea why it does this but I've been enjoying the free content for months now 💃 

There is a fix to it which is to add the sess field back in so that you'll 100% be authed into the account. This comes with drawbacks though. You can't use the script on a different IP address and user agent than the one you signed in with.

**Comment by monkjew** [comment]
I know it might be impossible, but is there a way to change anything in the config to try to keep changing the user it logs into?

**Comment by DIGITALCRIMINAL** [comment]
I spent a whole day trying to force it, but there's no way. It just happens by chance. Maybe the more accounts you create, the more different accounts you may auth into...

**Comment by wblondel** [comment]
Okay, now I understand why my folder is full of content of girls I'm not subscribed to.
I run the scraper twice a day to automatically download new content and it seems OnlyFans has a buggy API that authenticates you to another user once in a while.... crazy

**Comment by avekifes** [comment]
Now we just need to figure out how to exploit it.

**Comment by DIGITALCRIMINAL** [comment]
Been patched. 

F.
