### ISSUE TITLE
Help, please!

### ISSUE THREAD

**Issue by Arthmoc** [DIGITALCRIMINAL/OnlyFans#979]
When I started for the first time, it worked correctly, but with a problem, the download speed started at the maximum of my internet, and decreased until reaching byte/s.
https://prnt.sc/1158euy
And it's not my internet:
https://prnt.sc/1153vsk

The other problem; When I finished the program and tried to restart it, to see if my download normalized. This error occurred:

Traceback (most recent call last):
File "start_ofd.py", line 5, in <module>
main_test.check_config ()
File "C: \ Users \ User \ Documents \ OnlyFans-6.0 \ tests \ main_test.py", line 20, in check_config
import helpers.main_helper as main_helper
File "C: \ Users \ User \ Documents \ OnlyFans-6.0 \ helpers \ main_helper.py", line 4, in <module>
from deepdiff.deephash import DeepHash
ModuleNotFoundError: No module named 'deepdiff'

Traceback (most recent call last):
File "start_ofd.py", line 2, in <module>
import tests.main_test as main_test
File "C: \ Users \ User \ Documents \ OnlyFans-5.9.1 \ tests \ main_test.py", line 4, in <module>
import helpers.main_helper as main_helper
File "C: \ Users \ User \ Documents \ OnlyFans-5.9.1 \ helpers \ main_helper.py", line 4, in <module>
from deepdiff.deephash import DeepHash
ModuleNotFoundError: No module named 'deepdiff'

**Comment by Uberschall2519** [comment]
You need to install the modules in requirements.txt

`pip install -r requirements.txt`

**Comment by Arthmoc** [comment]
> You need to install the modules in requirements.txt
> 
> `pip install -r requirements.txt`

The requirements are already installed!

**Comment by Jarsky** [comment]
I get the same error in Linux (Ubuntu). I've been running an old version until just recently because the new one wouldn't work under Python 3.7. I just upgraded to Python 3.9 following the [linked discussion](https://github.com/DIGITALCRIMINAL/OnlyFans/discussions/889)

`user@server:~/OnlyFans$ python3.9 start_ofd.py
Traceback (most recent call last):
  File "/home/user/OnlyFans/start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "/home/user/OnlyFans/tests/main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "/home/user/OnlyFans/helpers/main_helper.py", line 5, in <module>
    from deepdiff.deephash import DeepHash
ModuleNotFoundError: No module named 'deepdiff'
`

`user@server:~/OnlyFans$ pip3 install -r requirements.txt
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.22.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 2)) (4.8.2)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (1.25.8)
Requirement already satisfied: win32-setctime in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 4)) (1.0.1)
Requirement already satisfied: pysocks in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 5)) (1.7.1)
Requirement already satisfied: psutil in /home/user/.local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (5.8.0)
Requirement already satisfied: python-dateutil in /home/user/.local/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (2.8.1)
Requirement already satisfied: lxml in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 8)) (4.5.0)
Requirement already satisfied: mergedeep in /home/user/.local/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (1.3.4)
Requirement already satisfied: jsonpickle in /home/user/.local/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (2.0.0)
Requirement already satisfied: deepdiff[murmur] in /home/user/.local/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (5.2.3)
  WARNING: deepdiff 5.2.3 does not provide the extra 'murmur'
Requirement already satisfied: numpy==1.19.3 in /home/user/.local/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (1.19.3)
Requirement already satisfied: ujson in /home/user/.local/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (4.0.2)
Requirement already satisfied: sqlalchemy==1.3.23 in /home/user/.local/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (1.3.23)
Requirement already satisfied: alembic in /home/user/.local/lib/python3.8/site-packages (from -r requirements.txt (line 15)) (1.5.4)
Requirement already satisfied: tqdm in /home/user/.local/lib/python3.8/site-packages (from -r requirements.txt (line 16)) (4.49.0)
Requirement already satisfied: selenium in /home/user/.local/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (3.141.0)
Requirement already satisfied: selenium-wire==2.1.2 in /home/user/.local/lib/python3.8/site-packages (from -r requirements.txt (line 18)) (2.1.2)
Requirement already satisfied: user_agent in /home/user/.local/lib/python3.8/site-packages (from -r requirements.txt (line 19)) (0.1.9)
Requirement already satisfied: soupsieve>=1.2 in /usr/local/lib/python3.8/dist-packages (from beautifulsoup4->-r requirements.txt (line 2)) (2.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil->-r requirements.txt (line 7)) (1.14.0)
Requirement already satisfied: ordered-set==4.0.2 in /home/user/.local/lib/python3.8/site-packages (from deepdiff[murmur]->-r requirements.txt (line 11)) (4.0.2)
Requirement already satisfied: Mako in /home/user/.local/lib/python3.8/site-packages (from alembic->-r requirements.txt (line 15)) (1.1.4)
Requirement already satisfied: python-editor>=0.3 in /home/user/.local/lib/python3.8/site-packages (from alembic->-r requirements.txt (line 15)) (1.0.4)
Requirement already satisfied: MarkupSafe>=0.9.2 in /home/user/.local/lib/python3.8/site-packages (from Mako->alembic->-r requirements.txt (line 15)) (1.1.1)`


I also tried installing deepdiff manually but still the same error

`user@server:~/OnlyFans$ sudo pip3 install deepdiff
Collecting deepdiff
  Downloading deepdiff-5.2.3-py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 2.3 MB/s
Collecting ordered-set==4.0.2
  Downloading ordered-set-4.0.2.tar.gz (10 kB)
Building wheels for collected packages: ordered-set
  Building wheel for ordered-set (setup.py) ... done
  Created wheel for ordered-set: filename=ordered_set-4.0.2-py2.py3-none-any.whl size=8209 sha256=a870aed2dd4acc0bc048244f996c083b62cfa26486bd9d467d4872                                             22ceba83d4
  Stored in directory: /root/.cache/pip/wheels/a1/09/42/0b963b1d5423ddc87cb4ba9f475e09838d3813300b52a866ea
Successfully built ordered-set
Installing collected packages: ordered-set, deepdiff
Successfully installed deepdiff-5.2.3 ordered-set-4.0.2`

**Comment by Jarsky** [comment]
OK I found running this, that deepdiff wasnt actually installed 

> user@server:~/OnlyFans$ pip3 list | grep -i deepdiff

So I ran this command, and now its showing installed

> user@server:~/OnlyFans$ pip3 install "deepdiff[cli]"
user@server:~/OnlyFans$ pip3 list | grep -i deepdiff
**deepdiff               5.2.3**

Now I get an ImportError as below, but hopefully this helps the OP

> user@server:~/OnlyFans$ python3 start_ofd.py
Traceback (most recent call last):
  File "/home/user/OnlyFans/start_ofd.py", line 10, in <module>
    main_test.check_config()
  File "/home/user/OnlyFans/tests/main_test.py", line 23, in check_config
    import helpers.main_helper as main_helper
  File "/home/user/OnlyFans/helpers/main_helper.py", line 6, in <module>
    from sqlalchemy.ext.declarative import api
ImportError: cannot import name 'api' from 'sqlalchemy.ext.declarative' (/home/user/.local/lib/python3.9/site-packages/sqlalchemy/ext/declarative/__init__.py)

**Comment by kimgia234** [comment]
The problem not come from here the python does not found any module deepdiff is the first called...

![image](https://user-images.githubusercontent.com/82375108/114374294-c6026980-9b83-11eb-890d-410dd8b3be1f.png)

I change manually the order and the same problem appear

**Comment by kimgia234** [comment]
finded! add python in your PATH env vars

**Comment by LunarPenguin** [comment]
Make sure you run the script using python 3.9 and have all the requirements installed @Arthmoc

your error message says the module `deepdiff` is not installed. I suggest installing it with `pip install --upgrade deepdiff` or the specific variation for your installation.

**Comment by DIGITALCRIMINAL** [comment]
Use latest version. DeepDiff is gone.
